version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '3306:3306'
  demo-java6-image:
    image: 'demo-java6-image:1.0'
    environment:
      - MARIADB_HOSTNAME=mariadb
      - MARIADB_ROOT_PASSWORD=bitnami
    ports:
      - '8000:8000'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
